# Challenge #9: Analytics Ranking

>For this challenge let’s look at ranking records when multiple records can have the same rank.

>The objective is to **determine the top 5 ranking based on the count, however since there are multiple rows with same count (similar to a round of golf) multiple people can be in the same place (Rank) if they have the same score.**

>We have listed this as a beginner challenge and I expect it will go very quickly for many of you. Let us know what you think, we are looking forward to hearing your feedback.

In [29]:
import pandas as pd

# import and preview output

output = pd.read_csv('output.csv', index_col = False)
df_output = pd.DataFrame(output)
df_output.head(25)

     First  count  Rank
0    JANET     17     1
1     MARK     17     1
2     PAUL     15     2
3    BRADY     14     3
4    CARLA     14     3
5    CHRIS     14     3
6    LINDA     14     3
7     DALE     13     4
8   LUANNE     13     4
9      GUY     11     5
10   LASKA     11     5
11  SHARON     11     5

In [30]:
# import and preview input

input = pd.read_csv('input.csv', index_col = False)
df = pd.DataFrame(input)
df.head(10)

    First  count
0     BOB      3
1   BRADY     14
2  BURTON      4
3   CARLA     14
4   CHRIS     14
5    DALE     13
6   DAVID      3
7      ED      4
8    ERIC      2
9     GUY     11

In [31]:
df['Rank'] = df['count'].rank(ascending=False, method='dense').astype(int)

In [32]:
df = df[df['Rank'] <= 5].sort_values(by='Rank').reset_index(drop=True)
df

     First  count  Rank
0    JANET     17     1
1     MARK     17     1
2     PAUL     15     2
3    BRADY     14     3
4    CARLA     14     3
5    CHRIS     14     3
6    LINDA     14     3
7     DALE     13     4
8   LUANNE     13     4
9      GUY     11     5
10   LASKA     11     5
11  SHARON     11     5

In [34]:
print(df.eq(output))

    First  count  Rank
0    True   True  True
1    True   True  True
2    True   True  True
3    True   True  True
4    True   True  True
5    True   True  True
6    True   True  True
7    True   True  True
8    True   True  True
9    True   True  True
10   True   True  True
11   True   True  True