# Challenge #11: Identify Logical Groups

>The use case:

>A manufacturing company receives customer complaint data on a daily basis from their call centers about the medical parts they distribute to their customers. The company monitors these comments to understand which parts and part groups have the highest complaint rate. This helps the company prioritize which parts to focus on from a development standpoint.

>In this exercise, take the customer complaint data and **identify which bucket the complaint falls within. The complaint can fall into multiple buckets and needs to be flagged as these complaints take highest priority. Create an aggregate view of which buckets or bucket pairings have the highest # of complaints.**

>This is only a subset of data so all records will not be assigned to buckets and can be ignored.

>**Update:** As of 9/26/19, this challenge start file and solution were modified.  Your solution will not match those posted by other Community members prior to this date.

In [127]:
import pandas as pd
import numpy as np

# import and preview output

output = pd.read_csv('output.csv', index_col = False)
df_output = pd.DataFrame(output)
df_output.head()

      Bucket(s)  Count
0        Screen      7
1  Tones,Screen      1
2       Trigger      1

In [128]:
# import and preview input 1

input1 = pd.read_csv('input1.csv', index_col = False)
df1 = pd.DataFrame(input1)
max_str = df1.Field_6.str.len().max()
pd.options.display.max_colwidth = max_str
df1

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Field_6
0                                                                                                                                                                                                                                                                                                                                                                                                                                                IT WAS REPORTED THAT DURING A PROCEDURE, IMMEDIATELY FOLLOWING THE LIGATION OF THE VASCULAR PEDICLES OF THE PATIENT'S BLADDER, THE SURGEON RECEIVED A WARNING MESSAGE ON THE SCREEN INDICATING THE INSTRUMENT WAS BROKEN. UPON REMOVAL OF THE INSTRUMENT, THE SURGEON OBSERVED THE INSTRUMENT'S BLADE WAS VISIBLY SEEN IN THE NECK. THERE WERE NO MISSING AND/OR FALLEN PIECES REPORTED. NO PATIENT HARM, ADVERSE OUTCOME OR INJURY WAS REPORTED.
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ON MAY 10 2015, THE REPORTER CONTACTED THE COMPANY ALLEGING THAT THE DISPLAY SCREEN WAS BLANK. THE DEVICE REPORTEDLY DID HAVE AUDIBLE TINES AND VIBRATION. THIS COMPLAINT IS BEING REPORTED BECAUSE THE REPORTED ISSUE WAS NOT RESOLVED WITH TROUBLESHOOTING. THERE WAS NO INDICATION THAT THE PRODUCT CAUSED OR CONTRIBUTED TO AN ADVERSE EVENT.
2                                                                                                                                                                                                                                                                                                                                                                                    DATE OF SUBMISSION 06/10/2011. DEVICE EVALUATION:THE DEVICE HAS BEEN RETURNED AND EVALUATED BY PRODUCT ANALYSIS ON 05/07/2011 WITH THE FOLLOWING FINDINGS:   INVESTIGATION REVEALED THAT THE BATTERY COMPARTMENT WAS CRACKED ALONG THE THREADS. UNRELATED TO THE COMPLAINT, THE DISPLAY SCREEN WAS FOUND TO BE DIM AND DISCOLORED. THE COMPANY HAS CONDUCTED A REVIEW OF THE DEVICE HISTORY RECORD FOR THIS DEVICE AND CONFIRMED THAT IT WAS OPERATING WITHIN REQUIRED SPECIFICATIONS AT THE TIME OF RELEASE.
3  DATE OF SUBMISSION 08/21/2017 - DEVICE EVALUATION: THE DEVICE HAS BEEN RETURNED AND EVALUATED BY PRODUCT ANALYSIS ON 07/21/2017 WITH THE FOLLOWING FINDINGS: A REVIEW OF THE DEVICE HISTORY SHOWED THAT MULTIPLE CALL SERVICE ALARMS RELATED TO THE BLANK SCREEN ISSUE WERE RECORDED ON 04/08/2017. DURING TESTING, THE DISPLAY FUNCTIONED NORMALLY WITH NO CONTRAST/COLOR PROBLEMS, MISSING SEGMENTS, OR INSTANCES OF A BLANK SCREEN. UNRELATED TO THE COMPLAINT, EVALUATION REVEALED THAT THE DIAL COMPARTMENT WAS CRACKED BETWEEN THE CASE SEAL AND CAP ON THE SIDE OF THE DEVICE. THE COMPLAINT OF THE BLANK DISPLAY SCREEN WAS OBSERVED IN THE DEVICE HISTORY BUT WAS NOT ABLE TO BE DUPLICATED DURING INVESTIGATION. ANIMAS HAS CONDUCTED A REVIEW OF THE DEVICE HISTORY RECORD FOR THIS DEVICE AND CONFIRMED THAT IT WAS OPERATING WITHIN REQUIRED SPECIFICATIONS AT THE TIME OF RELE...
4                                                                                                                                                                                                                                                                                                                                                                                                                                                          IT WAS REPORTED THAT THE DEVICE ALARMED AND INSULIN SQUIRTED OUT DURING THE MANUAL  PROCESS, BUT THE CUSTOMER WAS DISCONNECTED DURING THE PROCESS. THE PUMP CONTINUES MOVING FORWARD AFTER THE RESERVOIR MAKES CONTACT AND INSULIN SQUIRTS OUT, FOLLOWED BY THE ALARM. THE NUMBERS DID NOT APPEAR ON THE SCREEN, AND THE BEEPS COULD NOT BE HEARD. THE DRIVE SUPPORT DID NOT APPEAR TO BE DAMAGED. NO FURTHER INFORMATION WAS PROVIDED.
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ON JANUARY 18 2016, THE REPORTER CONTACTED THE COMPANY, ALLEGING A DISPLAY (BLANK SCREEN) ISSUE. THIS COMPLAINT IS BEING REPORTED BECAUSE THE REPORTED ISSUE WAS NOT RESOLVED WITH TROUBLESHOOTING. THERE WAS NO INDICATION THAT THE PRODUCT CAUSED OR CONTRIBUTED TO AN ADVERSE EVENT.
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       THE CUSTOMER REPORTED THAT AN NA540 DEVICE HAD A BLANK SCREEN. IT IS UNK IF THE MALFUNCTION OCCURRED DURING PT USE. ATTEMPTS HAVE BEEN MADE TO ACQUIRE ADD'L INFO REGARDING THIS COMPLAINT RECORD. ADD'L INFO HAS NOT BEEN MADE AVAILABLE BY THE CUSTOMER.
7                                                                                                                                                                                                                                                                                                               THE COMPANY RECEIVED INFORMATION THAT THIS DEVICE  EXHIBITED HIGH OUT-OF-RANGE PACING LEAD IMPEDANCE WHICH TRIGGERED THE LEAD SAFETY SWITCH ALONG WITH LOSS OF CAPTURE AT MAXIMUM DEVICE OUTPUTS. RADIOSCOPY WAS PERFORMED AND COMPANY ABC TECHNICAL SERVICES (TS) SUSPECTED A LEAD FRACTURE. X-RAY IMAGES APPEARED TO HAVE A SLIGHT SEPARATION IN THE LEAD CONDUCTOR. THE PATIENT WILL VISIT FOR FOLLOW-UP IN OVER A PERIOD OF TIME. THE PHYSICIAN DECIDED NOT TO PERFORM A REINTERVENTION AT THIS TIME. THE SYSTEM REMAINS IN SERVICE. NO ADVERSE PATIENT EFFECTS WERE REPORTED.
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           CUSTOMER STATED THAT THE DEVICE ALARMED BUTTON ERROR. THE CURRENT BLOOD GLUCOSE READING IS 84 MG/DL. CUSTOMER STATED THAT SHE WENT FOR LIGHT JOG AND THE INSULIN DEVICE'S SCREEN WAS AGAINST THE BODY. CUSTOMER WILL GO TO HOSPITAL BECAUSE SHE DOES NOT HAVE A BACKUP PLAN UNTIL THE INSULIN DEVICE ARRIVES. ADVISED THE CUSTOMER THAT THE INSULIN DEVICE WILL BE REPLACED. NOTHING FURTHER REPORTED.
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           REASON(S) FOR REVISION: PAIN. UPDATE - UPDATED SURGERY DATE AND REVISION DATE, TAKEN FROM CLAIMSUITE DATED 07/26/15 HAVE NOW CONFIRMED THAT THE REVISION TOOK PLACE ON 07/29/15. NEW FIELDS COMPLETED.

In [129]:
# import and preview input 2

input2 = pd.read_csv('input2.csv', index_col = False)
df2 = pd.DataFrame(input2)
df2.head()

    Search   Bucket
0     beep    Tones
1   screen   Screen
2  trigger  Trigger

In [130]:
df1['Field_6'] = df1['Field_6'].str.lower()
df1

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Field_6
0                                                                                                                                                                                                                                                                                                                                                                                                                                                it was reported that during a procedure, immediately following the ligation of the vascular pedicles of the patient's bladder, the surgeon received a warning message on the screen indicating the instrument was broken. upon removal of the instrument, the surgeon observed the instrument's blade was visibly seen in the neck. there were no missing and/or fallen pieces reported. no patient harm, adverse outcome or injury was reported.
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                on may 10 2015, the reporter contacted the company alleging that the display screen was blank. the device reportedly did have audible tines and vibration. this complaint is being reported because the reported issue was not resolved with troubleshooting. there was no indication that the product caused or contributed to an adverse event.
2                                                                                                                                                                                                                                                                                                                                                                                    date of submission 06/10/2011. device evaluation:the device has been returned and evaluated by product analysis on 05/07/2011 with the following findings:   investigation revealed that the battery compartment was cracked along the threads. unrelated to the complaint, the display screen was found to be dim and discolored. the company has conducted a review of the device history record for this device and confirmed that it was operating within required specifications at the time of release.
3  date of submission 08/21/2017 - device evaluation: the device has been returned and evaluated by product analysis on 07/21/2017 with the following findings: a review of the device history showed that multiple call service alarms related to the blank screen issue were recorded on 04/08/2017. during testing, the display functioned normally with no contrast/color problems, missing segments, or instances of a blank screen. unrelated to the complaint, evaluation revealed that the dial compartment was cracked between the case seal and cap on the side of the device. the complaint of the blank display screen was observed in the device history but was not able to be duplicated during investigation. animas has conducted a review of the device history record for this device and confirmed that it was operating within required specifications at the time of rele...
4                                                                                                                                                                                                                                                                                                                                                                                                                                                          it was reported that the device alarmed and insulin squirted out during the manual  process, but the customer was disconnected during the process. the pump continues moving forward after the reservoir makes contact and insulin squirts out, followed by the alarm. the numbers did not appear on the screen, and the beeps could not be heard. the drive support did not appear to be damaged. no further information was provided.
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          on january 18 2016, the reporter contacted the company, alleging a display (blank screen) issue. this complaint is being reported because the reported issue was not resolved with troubleshooting. there was no indication that the product caused or contributed to an adverse event.
6                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       the customer reported that an na540 device had a blank screen. it is unk if the malfunction occurred during pt use. attempts have been made to acquire add'l info regarding this complaint record. add'l info has not been made available by the customer.
7                                                                                                                                                                                                                                                                                                               the company received information that this device  exhibited high out-of-range pacing lead impedance which triggered the lead safety switch along with loss of capture at maximum device outputs. radioscopy was performed and company abc technical services (ts) suspected a lead fracture. x-ray images appeared to have a slight separation in the lead conductor. the patient will visit for follow-up in over a period of time. the physician decided not to perform a reintervention at this time. the system remains in service. no adverse patient effects were reported.
8                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           customer stated that the device alarmed button error. the current blood glucose reading is 84 mg/dl. customer stated that she went for light jog and the insulin device's screen was against the body. customer will go to hospital because she does not have a backup plan until the insulin device arrives. advised the customer that the insulin device will be replaced. nothing further reported.
9                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           reason(s) for revision: pain. update - updated surgery date and revision date, taken from claimsuite dated 07/26/15 have now confirmed that the revision took place on 07/29/15. new fields completed.

In [131]:
df1['beep'] = df1['Field_6'].str.match('.*beep.*')
df1['screen'] = df1['Field_6'].str.match('.*screen.*')
df1['trigger'] = df1['Field_6'].str.match('.*trigger.*')
df1

,Field_6,beep,screen,trigger
0,"it was reported that during a procedure, immediately following the ligation of the vascular pedicles of the patient's bladder, the surgeon received a warning message on the screen indicating the instrument was broken. upon removal of the instrument, the surgeon observed the instrument's blade was visibly seen in the neck. there were no missing and/or fallen pieces reported. no patient harm, adverse outcome or injury was reported.",False,True,False
1,"on may 10 2015, the reporter contacted the company alleging that the display screen was blank. the device reportedly did have audible tines and vibration. this complaint is being reported because the reported issue was not resolved with troubleshooting. there was no indication that the product caused or contributed to an adverse event.",False,True,False
2,"date of submission 06/10/2011. device evaluation:the device has been returned and evaluated by product analysis on 05/07/2011 with the following findings: investigation revealed that the battery compartment was cracked along the threads. unrelated to the complaint, the display screen was found to be dim and discolored. the company has conducted a review of the device history record for this device and confirmed that it was operating within required specifications at the time of release.",False,True,False
3,"date of submission 08/21/2017 - device evaluation: the device has been returned and evaluated by product analysis on 07/21/2017 with the following findings: a review of the device history showed that multiple call service alarms related to the blank screen issue were recorded on 04/08/2017. during testing, the display functioned normally with no contrast/color problems, missing segments, or instances of a blank screen. unrelated to the complaint, evaluation revealed that the dial compartment was cracked between the case seal and cap on the side of the device. the complaint of the blank display screen was observed in the device history but was not able to be duplicated during investigation. animas has conducted a review of the device history record for this device and confirmed that it was operating within required specifications at the time of rele...",False,True,False
4,"it was reported that the device alarmed and insulin squirted out during the manual process, but the customer was disconnected during the process. the pump continues moving forward after the reservoir makes contact and insulin squirts out, followed by the alarm. the numbers did not appear on the screen, and the beeps could not be heard. the drive support did not appear to be damaged. no further information was provided.",True,True,False
5,"on january 18 2016, the reporter contacted the company, alleging a display (blank screen) issue. this complaint is being reported because the reported issue was not resolved with troubleshooting. there was no indication that the product caused or contributed to an adverse event.",False,True,False
6,the customer reported that an na540 device had a blank screen. it is unk if the malfunction occurred during pt use. attempts have been made to acquire add'l info regarding this complaint record. add'l info has not been made available by the customer.,False,True,False
7,the company received information that this device exhibited high out-of-range pacing lead impedance which triggered the lead safety switch along with loss of capture at maximum device outputs. radioscopy was performed and company abc technical services (ts) suspected a lead fracture. x-ray images appeared to have a slight separation in the lead conductor. the patient will visit for follow-up in over a period of time. the physician decided not to perform a reintervention at this time. the system remains in service. no adverse patient effects were reported.,False,False,True
8,customer stated that the device alarmed button error. the current blood glucose reading is 84 mg/dl. customer stated that she went for light jog and the insulin device's screen was against the body. customer will go to hospital because she does not have a backup plan until the insulin device arrives. advised the customer that the insulin device will be replaced. nothing further reported.,False,True,False
9,"reason(s) for revision: pain. update - updated surgery date and revision date, taken from claimsuite dated 07/26/15 have now confirmed that the revision took place on 07/29/15. new fields completed.",False,False,False

In [132]:
df1['beep'].replace(to_replace=True, value='Tones', inplace=True)
df1['beep'].replace(to_replace=False, value=np.nan, inplace=True)
df1['screen'].replace(to_replace=True, value='Screen', inplace=True)
df1['screen'].replace(to_replace=False, value=np.nan, inplace=True)
df1['trigger'].replace(to_replace=True, value='Trigger', inplace=True)
df1['trigger'].replace(to_replace=False, value=np.nan, inplace=True)
df1

C:\Users\AdamSultanov\AppData\Local\Temp\ipykernel_28140\2341793672.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['beep'].replace(to_replace=True, value='Tones', inplace=True)
C:\Users\AdamSultanov\AppData\Local\Temp\ipykernel_28140\2341793672.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['screen'].replace(to_replace=True, value='Screen', inplace=True)
C:\Users\AdamSultanov\AppData\Local\Temp\ipykernel_28140\2341793672.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['trigger'].replace(to_replace=True, value='Trigger', inplace=True)

,Field_6,beep,screen,trigger
0,"it was reported that during a procedure, immediately following the ligation of the vascular pedicles of the patient's bladder, the surgeon received a warning message on the screen indicating the instrument was broken. upon removal of the instrument, the surgeon observed the instrument's blade was visibly seen in the neck. there were no missing and/or fallen pieces reported. no patient harm, adverse outcome or injury was reported.",NaN,Screen,NaN
1,"on may 10 2015, the reporter contacted the company alleging that the display screen was blank. the device reportedly did have audible tines and vibration. this complaint is being reported because the reported issue was not resolved with troubleshooting. there was no indication that the product caused or contributed to an adverse event.",NaN,Screen,NaN
2,"date of submission 06/10/2011. device evaluation:the device has been returned and evaluated by product analysis on 05/07/2011 with the following findings: investigation revealed that the battery compartment was cracked along the threads. unrelated to the complaint, the display screen was found to be dim and discolored. the company has conducted a review of the device history record for this device and confirmed that it was operating within required specifications at the time of release.",NaN,Screen,NaN
3,"date of submission 08/21/2017 - device evaluation: the device has been returned and evaluated by product analysis on 07/21/2017 with the following findings: a review of the device history showed that multiple call service alarms related to the blank screen issue were recorded on 04/08/2017. during testing, the display functioned normally with no contrast/color problems, missing segments, or instances of a blank screen. unrelated to the complaint, evaluation revealed that the dial compartment was cracked between the case seal and cap on the side of the device. the complaint of the blank display screen was observed in the device history but was not able to be duplicated during investigation. animas has conducted a review of the device history record for this device and confirmed that it was operating within required specifications at the time of rele...",NaN,Screen,NaN
4,"it was reported that the device alarmed and insulin squirted out during the manual process, but the customer was disconnected during the process. the pump continues moving forward after the reservoir makes contact and insulin squirts out, followed by the alarm. the numbers did not appear on the screen, and the beeps could not be heard. the drive support did not appear to be damaged. no further information was provided.",Tones,Screen,NaN
5,"on january 18 2016, the reporter contacted the company, alleging a display (blank screen) issue. this complaint is being reported because the reported issue was not resolved with troubleshooting. there was no indication that the product caused or contributed to an adverse event.",NaN,Screen,NaN
6,the customer reported that an na540 device had a blank screen. it is unk if the malfunction occurred during pt use. attempts have been made to acquire add'l info regarding this complaint record. add'l info has not been made available by the customer.,NaN,Screen,NaN
7,the company received information that this device exhibited high out-of-range pacing lead impedance which triggered the lead safety switch along with loss of capture at maximum device outputs. radioscopy was performed and company abc technical services (ts) suspected a lead fracture. x-ray images appeared to have a slight separation in the lead conductor. the patient will visit for follow-up in over a period of time. the physician decided not to perform a reintervention at this time. the system remains in service. no adverse patient effects were reported.,NaN,NaN,Trigger
8,customer stated that the device alarmed button error. the current blood glucose reading is 84 mg/dl. customer stated that she went for light jog and the insulin device's screen was against the body. customer will go to hospital because she does not have a backup plan until the insulin device arrives. advised the customer that the insulin device will be replaced. nothing further reported.,NaN,Screen,NaN
9,"reason(s) for revision: pain. update - updated surgery date and revision date, taken from claimsuite dated 07/26/15 have now confirmed that the revision took place on 07/29/15. new fields completed.",NaN,NaN,NaN

In [133]:
df1['Bucket(s)'] = df1[['beep', 'screen', 'trigger']].apply(lambda x: ','.join(x.dropna().astype(str).values), axis=1)
df1

,Field_6,beep,screen,trigger,Bucket(s)
0,"it was reported that during a procedure, immediately following the ligation of the vascular pedicles of the patient's bladder, the surgeon received a warning message on the screen indicating the instrument was broken. upon removal of the instrument, the surgeon observed the instrument's blade was visibly seen in the neck. there were no missing and/or fallen pieces reported. no patient harm, adverse outcome or injury was reported.",NaN,Screen,NaN,Screen
1,"on may 10 2015, the reporter contacted the company alleging that the display screen was blank. the device reportedly did have audible tines and vibration. this complaint is being reported because the reported issue was not resolved with troubleshooting. there was no indication that the product caused or contributed to an adverse event.",NaN,Screen,NaN,Screen
2,"date of submission 06/10/2011. device evaluation:the device has been returned and evaluated by product analysis on 05/07/2011 with the following findings: investigation revealed that the battery compartment was cracked along the threads. unrelated to the complaint, the display screen was found to be dim and discolored. the company has conducted a review of the device history record for this device and confirmed that it was operating within required specifications at the time of release.",NaN,Screen,NaN,Screen
3,"date of submission 08/21/2017 - device evaluation: the device has been returned and evaluated by product analysis on 07/21/2017 with the following findings: a review of the device history showed that multiple call service alarms related to the blank screen issue were recorded on 04/08/2017. during testing, the display functioned normally with no contrast/color problems, missing segments, or instances of a blank screen. unrelated to the complaint, evaluation revealed that the dial compartment was cracked between the case seal and cap on the side of the device. the complaint of the blank display screen was observed in the device history but was not able to be duplicated during investigation. animas has conducted a review of the device history record for this device and confirmed that it was operating within required specifications at the time of rele...",NaN,Screen,NaN,Screen
4,"it was reported that the device alarmed and insulin squirted out during the manual process, but the customer was disconnected during the process. the pump continues moving forward after the reservoir makes contact and insulin squirts out, followed by the alarm. the numbers did not appear on the screen, and the beeps could not be heard. the drive support did not appear to be damaged. no further information was provided.",Tones,Screen,NaN,"Tones,Screen"
5,"on january 18 2016, the reporter contacted the company, alleging a display (blank screen) issue. this complaint is being reported because the reported issue was not resolved with troubleshooting. there was no indication that the product caused or contributed to an adverse event.",NaN,Screen,NaN,Screen
6,the customer reported that an na540 device had a blank screen. it is unk if the malfunction occurred during pt use. attempts have been made to acquire add'l info regarding this complaint record. add'l info has not been made available by the customer.,NaN,Screen,NaN,Screen
7,the company received information that this device exhibited high out-of-range pacing lead impedance which triggered the lead safety switch along with loss of capture at maximum device outputs. radioscopy was performed and company abc technical services (ts) suspected a lead fracture. x-ray images appeared to have a slight separation in the lead conductor. the patient will visit for follow-up in over a period of time. the physician decided not to perform a reintervention at this time. the system remains in service. no adverse patient effects were reported.,NaN,NaN,Trigger,Trigger
8,customer stated that the device alarmed button error. the current blood glucose reading is 84 mg/dl. customer stated that she went for light jog and the insulin device's screen was against the body. customer will go to hospital because she does not have a backup plan until the insulin device arrives. advised the customer that the insulin device will be replaced. nothing further reported.,NaN,Screen,NaN,Screen
9,"reason(s) for revision: pain. update - updated surgery date and revision date, taken from claimsuite dated 07/26/15 have now confirmed that the revision took place on 07/29/15. new fields completed.",NaN,NaN,NaN,

In [134]:
df1 = df1[df1['Bucket(s)'] != '']
df1

,Field_6,beep,screen,trigger,Bucket(s)
0,"it was reported that during a procedure, immediately following the ligation of the vascular pedicles of the patient's bladder, the surgeon received a warning message on the screen indicating the instrument was broken. upon removal of the instrument, the surgeon observed the instrument's blade was visibly seen in the neck. there were no missing and/or fallen pieces reported. no patient harm, adverse outcome or injury was reported.",NaN,Screen,NaN,Screen
1,"on may 10 2015, the reporter contacted the company alleging that the display screen was blank. the device reportedly did have audible tines and vibration. this complaint is being reported because the reported issue was not resolved with troubleshooting. there was no indication that the product caused or contributed to an adverse event.",NaN,Screen,NaN,Screen
2,"date of submission 06/10/2011. device evaluation:the device has been returned and evaluated by product analysis on 05/07/2011 with the following findings: investigation revealed that the battery compartment was cracked along the threads. unrelated to the complaint, the display screen was found to be dim and discolored. the company has conducted a review of the device history record for this device and confirmed that it was operating within required specifications at the time of release.",NaN,Screen,NaN,Screen
3,"date of submission 08/21/2017 - device evaluation: the device has been returned and evaluated by product analysis on 07/21/2017 with the following findings: a review of the device history showed that multiple call service alarms related to the blank screen issue were recorded on 04/08/2017. during testing, the display functioned normally with no contrast/color problems, missing segments, or instances of a blank screen. unrelated to the complaint, evaluation revealed that the dial compartment was cracked between the case seal and cap on the side of the device. the complaint of the blank display screen was observed in the device history but was not able to be duplicated during investigation. animas has conducted a review of the device history record for this device and confirmed that it was operating within required specifications at the time of rele...",NaN,Screen,NaN,Screen
4,"it was reported that the device alarmed and insulin squirted out during the manual process, but the customer was disconnected during the process. the pump continues moving forward after the reservoir makes contact and insulin squirts out, followed by the alarm. the numbers did not appear on the screen, and the beeps could not be heard. the drive support did not appear to be damaged. no further information was provided.",Tones,Screen,NaN,"Tones,Screen"
5,"on january 18 2016, the reporter contacted the company, alleging a display (blank screen) issue. this complaint is being reported because the reported issue was not resolved with troubleshooting. there was no indication that the product caused or contributed to an adverse event.",NaN,Screen,NaN,Screen
6,the customer reported that an na540 device had a blank screen. it is unk if the malfunction occurred during pt use. attempts have been made to acquire add'l info regarding this complaint record. add'l info has not been made available by the customer.,NaN,Screen,NaN,Screen
7,the company received information that this device exhibited high out-of-range pacing lead impedance which triggered the lead safety switch along with loss of capture at maximum device outputs. radioscopy was performed and company abc technical services (ts) suspected a lead fracture. x-ray images appeared to have a slight separation in the lead conductor. the patient will visit for follow-up in over a period of time. the physician decided not to perform a reintervention at this time. the system remains in service. no adverse patient effects were reported.,NaN,NaN,Trigger,Trigger
8,customer stated that the device alarmed button error. the current blood glucose reading is 84 mg/dl. customer stated that she went for light jog and the insulin device's screen was against the body. customer will go to hospital because she does not have a backup plan until the insulin device arrives. advised the customer that the insulin device will be replaced. nothing further reported.,NaN,Screen,NaN,Screen

In [148]:
df = df1.groupby(by='Bucket(s)').count()
df = df.drop(['beep', 'screen', 'trigger'], axis=1)
df = df.rename({'Field_6': 'Count'}, axis=1)
df = df.reset_index()
df

      Bucket(s)  Count
0        Screen      7
1  Tones,Screen      1
2       Trigger      1

In [149]:
df.eq(output).all()

Bucket(s)    True
Count        True
dtype: bool