# Challenge #3: Running Averages

>We hope you enjoyed last week's challenge. For the third challenge, let’s look at creating 3 and 6 month running averages.

>The goal is to **create 3 and 6 month running averages for the values contained in columns: c.LK98, p.LK98, c.1K, p.1K, c.NLP3, and p.NLP3. Create the averages by RM Category.** 

>**Update:** As of 9/20/19, the start and solution files were updated.  Your solutions may not look like those posted by Community members prior to this date. 

### Sample Output:

In [107]:
import pandas as pd
# import and preview output
output = pd.read_csv('output.csv', index_col = False)
df_output = pd.DataFrame(output)
df_output.head(25)

    RecordID  Year  Month             Name    Value
0          1  2009      1      RM Category    10 rm
1          1  2009      1           C.LK98      218
2          1  2009      1           P.LK98  1178948
3          1  2009      1             C.1K       56
4          1  2009      1             D.1K   319316
5          1  2009      1           C.NLP3      162
6          1  2009      1           P.NLP3   859632
7          1  2009      1             C_1K       56
8          1  2009      1           C_LK98      218
9          1  2009      1           C_NLP3      162
10         1  2009      1             D_1K   319316
11         1  2009      1           P_LK98  1178948
12         1  2009      1           P_NLP3   859632
13         1  2009      1    Input_#3_C_1K       56
14         1  2009      1  Input_#3_C_LK98      218
15         1  2009      1  Input_#3_C_NLP3      162
16         1  2009      1    Input_#3_D_1K   319316
17         1  2009      1  Input_#3_P_LK98  1178948
18         1  2009      1  Input_#3_P_NLP3   859632
19         2  2009      2      RM Category    10 rm
20         2  2009      2           C.LK98      200
21         2  2009      2           P.LK98  1066974
22         2  2009      2             C.1K       44
23         2  2009      2             D.1K   248806
24         2  2009      2           C.NLP3      156

### Input:

In [108]:
# import and preview input
input = pd.read_csv('input.csv', index_col = False)
df = pd.DataFrame(input)
df

,RM Category,Year,Month,C.LK98,P.LK98,C.1K,D.1K,C.NLP3,P.NLP3
0,10 rm,2009,1,218.00,1178948.00,56.00,319316.00,162.00,859632.00
1,10 rm,2009,2,200.00,1066974.00,44.00,248806.00,156.00,818168.00
2,10 rm,2009,3,272.00,1399758.00,52.00,285730.00,220.00,1114028.00
3,10 rm,2009,4,178.00,996182.00,42.00,235730.00,136.00,760452.00
4,10 rm,2009,5,200.00,1117158.00,60.00,333908.00,140.00,783250.00
...,...,...,...,...,...,...,...,...,...
1363,75 rm,2014,8,NaN,NaN,NaN,NaN,NaN,NaN
1364,75 rm,2014,9,NaN,NaN,NaN,NaN,NaN,NaN
1365,75 rm,2014,10,NaN,NaN,NaN,NaN,NaN,NaN
1366,75 rm,2014,11,NaN,NaN,NaN,NaN,NaN,NaN
1367,75 rm,2014,12,NaN,NaN,NaN,NaN,NaN,NaN

In [109]:
# assign record ids

df["id"] = df.index + 1
df

,RM Category,Year,Month,C.LK98,P.LK98,C.1K,D.1K,C.NLP3,P.NLP3,id
0,10 rm,2009,1,218.00,1178948.00,56.00,319316.00,162.00,859632.00,1
1,10 rm,2009,2,200.00,1066974.00,44.00,248806.00,156.00,818168.00,2
2,10 rm,2009,3,272.00,1399758.00,52.00,285730.00,220.00,1114028.00,3
3,10 rm,2009,4,178.00,996182.00,42.00,235730.00,136.00,760452.00,4
4,10 rm,2009,5,200.00,1117158.00,60.00,333908.00,140.00,783250.00,5
...,...,...,...,...,...,...,...,...,...,...
1363,75 rm,2014,8,NaN,NaN,NaN,NaN,NaN,NaN,1364
1364,75 rm,2014,9,NaN,NaN,NaN,NaN,NaN,NaN,1365
1365,75 rm,2014,10,NaN,NaN,NaN,NaN,NaN,NaN,1366
1366,75 rm,2014,11,NaN,NaN,NaN,NaN,NaN,NaN,1367
1367,75 rm,2014,12,NaN,NaN,NaN,NaN,NaN,NaN,1368

In [110]:
# melt unpivots a dataframe from wide to long format

df = pd.melt(df, id_vars=["id", "RM Category", "Year", "Month"], var_name="Name", value_name="Value")
df

        id RM Category  Year  Month    Name  Value
0        1       10 rm  2009      1  C.LK98 218.00
1        2       10 rm  2009      2  C.LK98 200.00
2        3       10 rm  2009      3  C.LK98 272.00
3        4       10 rm  2009      4  C.LK98 178.00
4        5       10 rm  2009      5  C.LK98 200.00
...    ...         ...   ...    ...     ...    ...
8203  1364       75 rm  2014      8  P.NLP3    NaN
8204  1365       75 rm  2014      9  P.NLP3    NaN
8205  1366       75 rm  2014     10  P.NLP3    NaN
8206  1367       75 rm  2014     11  P.NLP3    NaN
8207  1368       75 rm  2014     12  P.NLP3    NaN

[8208 rows x 6 columns]

In [111]:
# fillna replaces NaN values
# isna().sum() checks columns for null values

df = df.fillna(0)
df.isna().sum()

id             0
RM Category    0
Year           0
Month          0
Name           0
Value          0
dtype: int64

In [112]:
# sort by category and record id

df.sort_values(by=["Name", "id"], inplace=True)
df

        id RM Category  Year  Month    Name  Value
2736     1       10 rm  2009      1    C.1K  56.00
2737     2       10 rm  2009      2    C.1K  44.00
2738     3       10 rm  2009      3    C.1K  52.00
2739     4       10 rm  2009      4    C.1K  42.00
2740     5       10 rm  2009      5    C.1K  60.00
...    ...         ...   ...    ...     ...    ...
8203  1364       75 rm  2014      8  P.NLP3   0.00
8204  1365       75 rm  2014      9  P.NLP3   0.00
8205  1366       75 rm  2014     10  P.NLP3   0.00
8206  1367       75 rm  2014     11  P.NLP3   0.00
8207  1368       75 rm  2014     12  P.NLP3   0.00

[8208 rows x 6 columns]

In [113]:
# calculate 3-month rolling average, with at least one observation to produce a non-null value

df["3m_avg"] = df["Value"].rolling(window=3, min_periods=1).mean()
df

        id RM Category  Year  Month    Name  Value     3m_avg
2736     1       10 rm  2009      1    C.1K  56.00      56.00
2737     2       10 rm  2009      2    C.1K  44.00      50.00
2738     3       10 rm  2009      3    C.1K  52.00      50.67
2739     4       10 rm  2009      4    C.1K  42.00      46.00
2740     5       10 rm  2009      5    C.1K  60.00      51.33
...    ...         ...   ...    ...     ...    ...        ...
8203  1364       75 rm  2014      8  P.NLP3   0.00 1370629.30
8204  1365       75 rm  2014      9  P.NLP3   0.00       0.00
8205  1366       75 rm  2014     10  P.NLP3   0.00       0.00
8206  1367       75 rm  2014     11  P.NLP3   0.00       0.00
8207  1368       75 rm  2014     12  P.NLP3   0.00       0.00

[8208 rows x 7 columns]

In [114]:
# format float to display at 0.00 instead of scientific notation

pd.set_option('display.float_format', lambda x: '%.2f' % x)
df

        id RM Category  Year  Month    Name  Value     3m_avg
2736     1       10 rm  2009      1    C.1K  56.00      56.00
2737     2       10 rm  2009      2    C.1K  44.00      50.00
2738     3       10 rm  2009      3    C.1K  52.00      50.67
2739     4       10 rm  2009      4    C.1K  42.00      46.00
2740     5       10 rm  2009      5    C.1K  60.00      51.33
...    ...         ...   ...    ...     ...    ...        ...
8203  1364       75 rm  2014      8  P.NLP3   0.00 1370629.30
8204  1365       75 rm  2014      9  P.NLP3   0.00       0.00
8205  1366       75 rm  2014     10  P.NLP3   0.00       0.00
8206  1367       75 rm  2014     11  P.NLP3   0.00       0.00
8207  1368       75 rm  2014     12  P.NLP3   0.00       0.00

[8208 rows x 7 columns]

In [115]:
# calculate 6-month rolling average, with at least one observation to produce a non-null value

df["6m_avg"] = df["Value"].rolling(window=6, min_periods=1).mean()
df

        id RM Category  Year  Month    Name  Value     3m_avg     6m_avg
2736     1       10 rm  2009      1    C.1K  56.00      56.00      56.00
2737     2       10 rm  2009      2    C.1K  44.00      50.00      50.00
2738     3       10 rm  2009      3    C.1K  52.00      50.67      50.67
2739     4       10 rm  2009      4    C.1K  42.00      46.00      48.50
2740     5       10 rm  2009      5    C.1K  60.00      51.33      50.80
...    ...         ...   ...    ...     ...    ...        ...        ...
8203  1364       75 rm  2014      8  P.NLP3   0.00 1370629.30 2452881.02
8204  1365       75 rm  2014      9  P.NLP3   0.00       0.00 1814921.68
8205  1366       75 rm  2014     10  P.NLP3   0.00       0.00 1261496.35
8206  1367       75 rm  2014     11  P.NLP3   0.00       0.00  685314.65
8207  1368       75 rm  2014     12  P.NLP3   0.00       0.00       0.00

[8208 rows x 8 columns]

In [116]:
# reset dataframe index, print truncated or scrollable element

df = df.reset_index(drop=True)
print(df.to_string())

        id   RM Category  Year  Month    Name       Value     3m_avg     6m_avg
0        1         10 rm  2009      1    C.1K       56.00      56.00      56.00
1        2         10 rm  2009      2    C.1K       44.00      50.00      50.00
2        3         10 rm  2009      3    C.1K       52.00      50.67      50.67
3        4         10 rm  2009      4    C.1K       42.00      46.00      48.50
4        5         10 rm  2009      5    C.1K       60.00      51.33      50.80
5        6         10 rm  2009      6    C.1K       70.00      57.33      54.00
6        7         10 rm  2009      7    C.1K       68.00      66.00      56.00
7        8         10 rm  2009      8    C.1K       48.00      62.00      56.67
8        9         10 rm  2009      9    C.1K       74.00      63.33      60.33
9       10         10 rm  2009     10    C.1K       74.00      65.33      65.67
10      11         10 rm  2009     11    C.1K       66.00      71.33      66.67
11      12         10 rm  2009     12    C.1K       80.00      73.33      68.33
12      13         10 rm  2010      1    C.1K       40.00      62.00      63.67
13      14         10 rm  2010      2    C.1K       42.00      54.00      62.67
14      15         10 rm  2010      3    C.1K       58.00      46.67      60.00
15      16         10 rm  2010      4    C.1K       50.00      50.00      56.00
16      17         10 rm  2010      5    C.1K       54.00      54.00      54.00
17      18         10 rm  2010      6    C.1K       52.00      52.00      49.33
18      19         10 rm  2010      7    C.1K       64.00      56.67      53.33
19      20         10 rm  2010      8    C.1K       60.00      58.67      56.33
20      21         10 rm  2010      9    C.1K       64.00      62.67      57.33
21      22         10 rm  2010     10    C.1K       54.00      59.33      58.00
22      23         10 rm  2010     11    C.1K       66.00      61.33      60.00
23      24         10 rm  2010     12    C.1K       88.00      69.33      66.00
24      25         10 rm  2011      1    C.1K       46.00      66.67      63.00
25      26         10 rm  2011      2    C.1K       46.00      60.00      60.67
26      27         10 rm  2011      3    C.1K       72.00      54.67      62.00
27      28         10 rm  2011      4    C.1K       42.00      53.33      60.00
28      29         10 rm  2011      5    C.1K       52.00      55.33      57.67
29      30         10 rm  2011      6    C.1K       54.00      49.33      52.00
30      31         10 rm  2011      7    C.1K       48.00      51.33      52.33
31      32         10 rm  2011      8    C.1K       80.00      60.67      58.00
32      33         10 rm  2011      9    C.1K       92.00      73.33      61.33
33      34         10 rm  2011     10    C.1K       48.00      73.33      62.33
34      35         10 rm  2011     11    C.1K       86.00      75.33      68.00
35      36         10 rm  2011     12    C.1K       86.00      73.33      73.33
36      37         10 rm  2012      1    C.1K       42.00      71.33      72.33
37      38         10 rm  2012      2    C.1K      110.00      79.33      77.33
38      39         10 rm  2012      3    C.1K      106.00      86.00      79.67
39      40         10 rm  2012      4    C.1K       62.00      92.67      82.00
40      41         10 rm  2012      5    C.1K       74.00      80.67      80.00
41      42         10 rm  2012      6    C.1K       72.00      69.33      77.67
42      43         10 rm  2012      7    C.1K       98.00      81.33      87.00
43      44         10 rm  2012      8    C.1K       76.00      82.00      81.33
44      45         10 rm  2012      9    C.1K       52.00      75.33      72.33
45      46         10 rm  2012     10    C.1K       62.00      63.33      72.33
46      47         10 rm  2012     11    C.1K       92.00      68.67      75.33
47      48         10 rm  2012     12    C.1K      104.00      86.00      80.67
48      49         10 rm  2013      1    C.1K       76.00      90.67      77.00
49      50         10 rm  2013      2    C.1K      112.00      97.33      83.00
50      51         10 rm  2013      3    C.1K       82.00      90.00      88.00
51      52         10 rm  2013      4    C.1K      100.00      98.00      94.33
52      53         10 rm  2013      5    C.1K      104.00      95.33      96.33
53      54         10 rm  2013      6    C.1K       86.00      96.67      93.33
54      55         10 rm  2013      7    C.1K       92.00      94.00      96.00
55      56         10 rm  2013      8    C.1K       94.00      90.67      93.00
56      57         10 rm  2013      9    C.1K       96.00      94.00      95.33
57      58         10 rm  2013     10    C.1K       76.00      88.67      91.33
58      59         10 rm  2013     11    C.1K       92.00      88.00      89.33
59      60         10 rm  2013     12    C.1K      100.00      89.33      91.67
60      61         10 rm  2014      1    C.1K      110.00     100.67      94.67
61      62         10 rm  2014      2    C.1K       94.00     101.33      94.67
62      63         10 rm  2014      3    C.1K       86.00      96.67      93.00
63      64         10 rm  2014      4    C.1K      104.00      94.67      97.67
64      65         10 rm  2014      5    C.1K       92.00      94.00      97.67
65      66         10 rm  2014      6    C.1K      118.00     104.67     100.67
66      67         10 rm  2014      7    C.1K        0.00      70.00      82.33
67      68         10 rm  2014      8    C.1K        0.00      39.33      66.67
68      69         10 rm  2014      9    C.1K        0.00       0.00      52.33
69      70         10 rm  2014     10    C.1K        0.00       0.00      35.00
70      71         10 rm  2014     11    C.1K        0.00       0.00      19.67
71      72         10 rm  2014     12    C.1K        0.00       0.00       0.00
72      73        100 rm  2009      1    C.1K       42.00      14.00       7.00
73      74        100 rm  2009      2    C.1K       24.00      22.00      11.00
74      75        100 rm  2009      3    C.1K       40.00      35.33      17.67
75      76        100 rm  2009      4    C.1K       36.00      33.33      23.67
76      77        100 rm  2009      5    C.1K       26.00      34.00      28.00
77      78        100 rm  2009      6    C.1K       50.00      37.33      36.33
78      79        100 rm  2009      7    C.1K       22.00      32.67      33.00
79      80        100 rm  2009      8    C.1K       38.00      36.67      35.33
80      81        100 rm  2009      9    C.1K       24.00      28.00      32.67
81      82        100 rm  2009     10    C.1K       34.00      32.00      32.33
82      83        100 rm  2009     11    C.1K       26.00      28.00      32.33
83      84        100 rm  2009     12    C.1K       26.00      28.67      28.33
84      85        100 rm  2010      1    C.1K       14.00      22.00      27.00
85      86        100 rm  2010      2    C.1K       50.00      30.00      29.00
86      87        100 rm  2010      3    C.1K       52.00      38.67      33.67
87      88        100 rm  2010      4    C.1K       46.00      49.33      35.67
88      89        100 rm  2010      5    C.1K       46.00      48.00      39.00
89      90        100 rm  2010      6    C.1K       40.00      44.00      41.33
90      91        100 rm  2010      7    C.1K       34.00      40.00      44.67
91      92        100 rm  2010      8    C.1K       42.00      38.67      43.33
92      93        100 rm  2010      9    C.1K       84.00      53.33      48.67
93      94        100 rm  2010     10    C.1K       52.00      59.33      49.67
94      95        100 rm  2010     11    C.1K       44.00      60.00      49.33
95      96        100 rm  2010     12    C.1K       74.00      56.67      55.00
96      97        100 rm  2011      1    C.1K       30.00      49.33      54.33
97      98        100 rm  2011      2    C.1K       56.00      53.33      56.67
98      99        100 rm  2011      3    C.1K       62.00      49.33      53.00
99     100        100 rm  2011      4    C.1K       50.00      56.00      52.67
100    101        100 rm  2011      5    C.1K       46.00      52.67      53.00
101    102        100 rm  2011      6    C.1K       52.00      49.33      49.33
102    103        100 rm  2011      7    C.1K       44.00      47.33      51.67
103    104        100 rm  2011      8    C.1K       52.00      49.33      51.00
104    105        100 rm  2011      9    C.1K       66.00      54.00      51.67
105    106        100 rm  2011     10    C.1K      106.00      74.67      61.00
106    107        100 rm  2011     11    C.1K       70.00      80.67      65.00
107    108        100 rm  2011     12    C.1K       82.00      86.00      70.00
108    109        100 rm  2012      1    C.1K       26.00      59.33      67.00
109    110        100 rm  2012      2    C.1K       58.00      55.33      68.00
110    111        100 rm  2012      3    C.1K       48.00      44.00      65.00
111    112        100 rm  2012      4    C.1K       88.00      64.67      62.00
112    113        100 rm  2012      5    C.1K       84.00      73.33      64.33
113    114        100 rm  2012      6    C.1K       90.00      87.33      65.67
114    115        100 rm  2012      7    C.1K       52.00      75.33      70.00
115    116        100 rm  2012      8    C.1K       58.00      66.67      70.00
116    117        100 rm  2012      9    C.1K       56.00      55.33      71.33
117    118        100 rm  2012     10    C.1K       78.00      64.00      69.67
118    119        100 rm  2012     11    C.1K       84.00      72.67      69.67
119    120        100 rm  2012     12    C.1K       96.00      86.00      70.67
120    121        100 rm  2013      1    C.1K       48.00      76.00      70.00
121    122        100 rm  2013      2    C.1K       54.00      66.00      69.33
122    123        100 rm  2013      3    C.1K       70.00      57.33      71.67
123    124        100 rm  2013      4    C.1K       78.00      67.33      71.67
124    125        100 rm  2013      5    C.1K       70.00      72.67      69.33
125    126        100 rm  2013      6    C.1K      104.00      84.00      70.67
126    127        100 rm  2013      7    C.1K       90.00      88.00      77.67
127    128        100 rm  2013      8    C.1K       82.00      92.00      82.33
128    129        100 rm  2013      9    C.1K       86.00      86.00      85.00
129    130        100 rm  2013     10    C.1K       68.00      78.67      83.33
130    131        100 rm  2013     11    C.1K       70.00      74.67      83.33
131    132        100 rm  2013     12    C.1K       80.00      72.67      79.33
132    133        100 rm  2014      1    C.1K       40.00      63.33      71.00
133    134        100 rm  2014      2    C.1K       42.00      54.00      64.33
134    135        100 rm  2014      3    C.1K       66.00      49.33      61.00
135    136        100 rm  2014      4    C.1K       62.00      56.67      60.00
136    137        100 rm  2014      5    C.1K       54.00      60.67      57.33
137    138        100 rm  2014      6    C.1K      106.00      74.00      61.67
138    139        100 rm  2014      7    C.1K        0.00      53.33      55.00
139    140        100 rm  2014      8    C.1K        0.00      35.33      48.00
140    141        100 rm  2014      9    C.1K        0.00       0.00      37.00
141    142        100 rm  2014     10    C.1K        0.00       0.00      26.67
142    143        100 rm  2014     11    C.1K        0.00       0.00      17.67
143    144        100 rm  2014     12    C.1K        0.00       0.00       0.00
144    145        125 rm  2009      1    C.1K        8.00       2.67       1.33
145    146        125 rm  2009      2    C.1K       16.00       8.00       4.00
146    147        125 rm  2009      3    C.1K       20.00      14.67       7.33
147    148        125 rm  2009      4    C.1K       12.00      16.00       9.33
148    149        125 rm  2009      5    C.1K       16.00      16.00      12.00
149    150        125 rm  2009      6    C.1K        8.00      12.00      13.33
150    151        125 rm  2009      7    C.1K       20.00      14.67      15.33
151    152        125 rm  2009      8    C.1K        4.00      10.67      13.33
152    153        125 rm  2009      9    C.1K       16.00      13.33      12.67
153    154        125 rm  2009     10    C.1K       10.00      10.00      12.33
154    155        125 rm  2009     11    C.1K       14.00      13.33      12.00
155    156        125 rm  2009     12    C.1K       18.00      14.00      13.67
156    157        125 rm  2010      1    C.1K       14.00      15.33      12.67
157    158        125 rm  2010      2    C.1K       10.00      14.00      13.67
158    159        125 rm  2010      3    C.1K        6.00      10.00      12.00
159    160        125 rm  2010      4    C.1K       14.00      10.00      12.67
160    161        125 rm  2010      5    C.1K        8.00       9.33      11.67
161    162        125 rm  2010      6    C.1K        4.00       8.67       9.33
162    163        125 rm  2010      7    C.1K       12.00       8.00       9.00
163    164        125 rm  2010      8    C.1K        4.00       6.67       8.00
164    165        125 rm  2010      9    C.1K        4.00       6.67       7.67
165    166        125 rm  2010     10    C.1K       22.00      10.00       9.00
166    167        125 rm  2010     11    C.1K       26.00      17.33      12.00
167    168        125 rm  2010     12    C.1K       30.00      26.00      16.33
168    169        125 rm  2011      1    C.1K        6.00      20.67      15.33
169    170        125 rm  2011      2    C.1K       16.00      17.33      17.33
170    171        125 rm  2011      3    C.1K        8.00      10.00      18.00
171    172        125 rm  2011      4    C.1K       22.00      15.33      18.00
172    173        125 rm  2011      5    C.1K        8.00      12.67      15.00
173    174        125 rm  2011      6    C.1K       16.00      15.33      12.67
174    175        125 rm  2011      7    C.1K       10.00      11.33      13.33
175    176        125 rm  2011      8    C.1K       18.00      14.67      13.67
176    177        125 rm  2011      9    C.1K       22.00      16.67      16.00
177    178        125 rm  2011     10    C.1K       20.00      20.00      15.67
178    179        125 rm  2011     11    C.1K       32.00      24.67      19.67
179    180        125 rm  2011     12    C.1K       30.00      27.33      22.00
180    181        125 rm  2012      1    C.1K       12.00      24.67      22.33
181    182        125 rm  2012      2    C.1K       10.00      17.33      21.00
182    183        125 rm  2012      3    C.1K       30.00      17.33      22.33
183    184        125 rm  2012      4    C.1K       18.00      19.33      22.00
184    185        125 rm  2012      5    C.1K       12.00      20.00      18.67
185    186        125 rm  2012      6    C.1K       20.00      16.67      17.00
186    187        125 rm  2012      7    C.1K       14.00      15.33      17.33
187    188        125 rm  2012      8    C.1K       12.00      15.33      17.67
188    189        125 rm  2012      9    C.1K       12.00      12.67      14.67
189    190        125 rm  2012     10    C.1K       12.00      12.00      13.67
190    191        125 rm  2012     11    C.1K       28.00      17.33      16.33
191    192        125 rm  2012     12    C.1K       20.00      20.00      16.33
192    193        125 rm  2013      1    C.1K       12.00      20.00      16.00
193    194        125 rm  2013      2    C.1K       16.00      16.00      16.67
194    195        125 rm  2013      3    C.1K       16.00      14.67      17.33
195    196        125 rm  2013      4    C.1K       10.00      14.00      17.00
196    197        125 rm  2013      5    C.1K       12.00      12.67      14.33
197    198        125 rm  2013      6    C.1K       12.00      11.33      13.00
198    199        125 rm  2013      7    C.1K       18.00      14.00      14.00
199    200        125 rm  2013      8    C.1K        6.00      12.00      12.33
200    201        125 rm  2013      9    C.1K       18.00      14.00      12.67
201    202        125 rm  2013     10    C.1K       14.00      12.67      13.33
202    203        125 rm  2013     11    C.1K       10.00      14.00      13.00
203    204        125 rm  2013     12    C.1K       14.00      12.67      13.33
204    205        125 rm  2014      1    C.1K       12.00      12.00      12.33
205    206        125 rm  2014      2    C.1K       16.00      14.00      14.00
206    207        125 rm  2014      3    C.1K       28.00      18.67      15.67
207    208        125 rm  2014      4    C.1K       12.00      18.67      15.33
208    209        125 rm  2014      5    C.1K        4.00      14.67      14.33
209    210        125 rm  2014      6    C.1K       16.00      10.67      14.67
210    211        125 rm  2014      7    C.1K        0.00       6.67      12.67
211    212        125 rm  2014      8    C.1K        0.00       5.33      10.00
212    213        125 rm  2014      9    C.1K        0.00       0.00       5.33
213    214        125 rm  2014     10    C.1K        0.00       0.00       3.33
214    215        125 rm  2014     11    C.1K        0.00       0.00       2.67
215    216        125 rm  2014     12    C.1K        0.00       0.00       0.00
216    217         15 rm  2009      1    C.1K      122.00      40.67      20.33
217    218         15 rm  2009      2    C.1K       90.00      70.67      35.33
218    219         15 rm  2009      3    C.1K      128.00     113.33      56.67
219    220         15 rm  2009      4    C.1K       94.00     104.00      72.33
220    221         15 rm  2009      5    C.1K      110.00     110.67      90.67
221    222         15 rm  2009      6    C.1K       94.00      99.33     106.33
222    223         15 rm  2009      7    C.1K      106.00     103.33     103.67
223    224         15 rm  2009      8    C.1K      106.00     102.00     106.33
224    225         15 rm  2009      9    C.1K      106.00     106.00     102.67
225    226         15 rm  2009     10    C.1K      110.00     107.33     105.33
226    227         15 rm  2009     11    C.1K      138.00     118.00     110.00
227    228         15 rm  2009     12    C.1K      170.00     139.33     122.67
228    229         15 rm  2010      1    C.1K      112.00     140.00     123.67
229    230         15 rm  2010      2    C.1K      120.00     134.00     126.00
230    231         15 rm  2010      3    C.1K      106.00     112.67     126.00
231    232         15 rm  2010      4    C.1K      128.00     118.00     129.00
232    233         15 rm  2010      5    C.1K       76.00     103.33     118.67
233    234         15 rm  2010      6    C.1K      122.00     108.67     110.67
234    235         15 rm  2010      7    C.1K      116.00     104.67     111.33
235    236         15 rm  2010      8    C.1K      178.00     138.67     121.00
236    237         15 rm  2010      9    C.1K      132.00     142.00     125.33
237    238         15 rm  2010     10    C.1K      114.00     141.33     123.00
238    239         15 rm  2010     11    C.1K      124.00     123.33     131.00
239    240         15 rm  2010     12    C.1K      206.00     148.00     145.00
240    241         15 rm  2011      1    C.1K      126.00     152.00     146.67
241    242         15 rm  2011      2    C.1K       88.00     140.00     131.67
242    243         15 rm  2011      3    C.1K      156.00     123.33     135.67
243    244         15 rm  2011      4    C.1K      140.00     128.00     140.00
244    245         15 rm  2011      5    C.1K      158.00     151.33     145.67
245    246         15 rm  2011      6    C.1K      152.00     150.00     136.67
246    247         15 rm  2011      7    C.1K      138.00     149.33     138.67
247    248         15 rm  2011      8    C.1K      152.00     147.33     149.33
248    249         15 rm  2011      9    C.1K      186.00     158.67     154.33