# Challenge #3: Running Averages

>We hope you enjoyed last week's challenge. For the third challenge, let’s look at creating 3 and 6 month running averages.

>The goal is to **create 3 and 6 month running averages for the values contained in columns: c.LK98, p.LK98, c.1K, p.1K, c.NLP3, and p.NLP3. Create the averages by RM Category.** 

>**Update:** As of 9/20/19, the start and solution files were updated.  Your solutions may not look like those posted by Community members prior to this date. 

### Output:

In [1]:
import pandas as pd
# import and preview output
output = pd.read_csv('output.csv', index_col = False)
df_output = pd.DataFrame(output)
df_output.head(25)

    RecordID  Year  Month             Name    Value
0          1  2009      1      RM Category    10 rm
1          1  2009      1           C.LK98      218
2          1  2009      1           P.LK98  1178948
3          1  2009      1             C.1K       56
4          1  2009      1             D.1K   319316
5          1  2009      1           C.NLP3      162
6          1  2009      1           P.NLP3   859632
7          1  2009      1             C_1K       56
8          1  2009      1           C_LK98      218
9          1  2009      1           C_NLP3      162
10         1  2009      1             D_1K   319316
11         1  2009      1           P_LK98  1178948
12         1  2009      1           P_NLP3   859632
13         1  2009      1    Input_#3_C_1K       56
14         1  2009      1  Input_#3_C_LK98      218
15         1  2009      1  Input_#3_C_NLP3      162
16         1  2009      1    Input_#3_D_1K   319316
17         1  2009      1  Input_#3_P_LK98  1178948
18         1  2009      1  Input_#3_P_NLP3   859632
19         2  2009      2      RM Category    10 rm
20         2  2009      2           C.LK98      200
21         2  2009      2           P.LK98  1066974
22         2  2009      2             C.1K       44
23         2  2009      2             D.1K   248806
24         2  2009      2           C.NLP3      156

### Input:

In [2]:
# import and preview input
input = pd.read_csv('input.csv', index_col = False)
df = pd.DataFrame(input)
df

,RM Category,Year,Month,C.LK98,P.LK98,C.1K,D.1K,C.NLP3,P.NLP3
0,10 rm,2009,1,218.0,1178948.0,56.0,319316.0,162.0,859632.0
1,10 rm,2009,2,200.0,1066974.0,44.0,248806.0,156.0,818168.0
2,10 rm,2009,3,272.0,1399758.0,52.0,285730.0,220.0,1114028.0
3,10 rm,2009,4,178.0,996182.0,42.0,235730.0,136.0,760452.0
4,10 rm,2009,5,200.0,1117158.0,60.0,333908.0,140.0,783250.0
...,...,...,...,...,...,...,...,...,...
1363,75 rm,2014,8,NaN,NaN,NaN,NaN,NaN,NaN
1364,75 rm,2014,9,NaN,NaN,NaN,NaN,NaN,NaN
1365,75 rm,2014,10,NaN,NaN,NaN,NaN,NaN,NaN
1366,75 rm,2014,11,NaN,NaN,NaN,NaN,NaN,NaN
1367,75 rm,2014,12,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df["id"] = df.index + 1
df

,RM Category,Year,Month,C.LK98,P.LK98,C.1K,D.1K,C.NLP3,P.NLP3,id
0,10 rm,2009,1,218.0,1178948.0,56.0,319316.0,162.0,859632.0,1
1,10 rm,2009,2,200.0,1066974.0,44.0,248806.0,156.0,818168.0,2
2,10 rm,2009,3,272.0,1399758.0,52.0,285730.0,220.0,1114028.0,3
3,10 rm,2009,4,178.0,996182.0,42.0,235730.0,136.0,760452.0,4
4,10 rm,2009,5,200.0,1117158.0,60.0,333908.0,140.0,783250.0,5
...,...,...,...,...,...,...,...,...,...,...
1363,75 rm,2014,8,NaN,NaN,NaN,NaN,NaN,NaN,1364
1364,75 rm,2014,9,NaN,NaN,NaN,NaN,NaN,NaN,1365
1365,75 rm,2014,10,NaN,NaN,NaN,NaN,NaN,NaN,1366
1366,75 rm,2014,11,NaN,NaN,NaN,NaN,NaN,NaN,1367
1367,75 rm,2014,12,NaN,NaN,NaN,NaN,NaN,NaN,1368

In [4]:
df_stack = df.set_index(["id", "RM Category", "Year", "Month"])
df_stack

,,,,C.LK98,P.LK98,C.1K,D.1K,C.NLP3,P.NLP3
id,RM Category,Year,Month,,,,,,
1,10 rm,2009,1,218.0,1178948.0,56.0,319316.0,162.0,859632.0
2,10 rm,2009,2,200.0,1066974.0,44.0,248806.0,156.0,818168.0
3,10 rm,2009,3,272.0,1399758.0,52.0,285730.0,220.0,1114028.0
4,10 rm,2009,4,178.0,996182.0,42.0,235730.0,136.0,760452.0
5,10 rm,2009,5,200.0,1117158.0,60.0,333908.0,140.0,783250.0
...,...,...,...,...,...,...,...,...,...
1364,75 rm,2014,8,NaN,NaN,NaN,NaN,NaN,NaN
1365,75 rm,2014,9,NaN,NaN,NaN,NaN,NaN,NaN
1366,75 rm,2014,10,NaN,NaN,NaN,NaN,NaN,NaN
1367,75 rm,2014,11,NaN,NaN,NaN,NaN,NaN,NaN
1368,75 rm,2014,12,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_stack.isna().sum()

C.LK98    120
P.LK98    120
C.1K      115
D.1K      115
C.NLP3    121
P.NLP3    121
dtype: int64

In [6]:
df_stack = df_stack.fillna(0)
df_stack.isna().sum()

C.LK98    0
P.LK98    0
C.1K      0
D.1K      0
C.NLP3    0
P.NLP3    0
dtype: int64

In [7]:
df_stack.tail(10)

,,,,C.LK98,P.LK98,C.1K,D.1K,C.NLP3,P.NLP3
id,RM Category,Year,Month,,,,,,
1359,75 rm,2014,3,200.0,5063774.0,50.0,1236018.0,150.0,3827756.0
1360,75 rm,2014,4,196.0,5210746.0,68.0,1890194.0,128.0,3320552.0
1361,75 rm,2014,5,186.0,4572086.0,44.0,1114995.8,142.0,3457090.2
1362,75 rm,2014,6,208.0,5458388.0,54.0,1346500.1,154.0,4111887.9
1363,75 rm,2014,7,0.0,0.0,0.0,0.0,0.0,0.0
1364,75 rm,2014,8,0.0,0.0,0.0,0.0,0.0,0.0
1365,75 rm,2014,9,0.0,0.0,0.0,0.0,0.0,0.0
1366,75 rm,2014,10,0.0,0.0,0.0,0.0,0.0,0.0
1367,75 rm,2014,11,0.0,0.0,0.0,0.0,0.0,0.0
1368,75 rm,2014,12,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
df_stack = df_stack.stack()

In [9]:
df_stack

id    RM Category  Year  Month
1     10 rm        2009  1      C.LK98        218.0
                                P.LK98    1178948.0
                                C.1K           56.0
                                D.1K       319316.0
                                C.NLP3        162.0
                                            ...
1368  75 rm        2014  12     P.LK98          0.0
                                C.1K            0.0
                                D.1K            0.0
                                C.NLP3          0.0
                                P.NLP3          0.0
Length: 8208, dtype: float64

In [10]:
df

,RM Category,Year,Month,C.LK98,P.LK98,C.1K,D.1K,C.NLP3,P.NLP3,id
0,10 rm,2009,1,218.0,1178948.0,56.0,319316.0,162.0,859632.0,1
1,10 rm,2009,2,200.0,1066974.0,44.0,248806.0,156.0,818168.0,2
2,10 rm,2009,3,272.0,1399758.0,52.0,285730.0,220.0,1114028.0,3
3,10 rm,2009,4,178.0,996182.0,42.0,235730.0,136.0,760452.0,4
4,10 rm,2009,5,200.0,1117158.0,60.0,333908.0,140.0,783250.0,5
...,...,...,...,...,...,...,...,...,...,...
1363,75 rm,2014,8,NaN,NaN,NaN,NaN,NaN,NaN,1364
1364,75 rm,2014,9,NaN,NaN,NaN,NaN,NaN,NaN,1365
1365,75 rm,2014,10,NaN,NaN,NaN,NaN,NaN,NaN,1366
1366,75 rm,2014,11,NaN,NaN,NaN,NaN,NaN,NaN,1367
1367,75 rm,2014,12,NaN,NaN,NaN,NaN,NaN,NaN,1368

In [11]:
df_melt = pd.melt(df, id_vars=["id", "RM Category", "Year", "Month"], var_name="Name", value_name="Value")

In [12]:
df_melt = df_melt.fillna(0)
df_melt.isna().sum()

id             0
RM Category    0
Year           0
Month          0
Name           0
Value          0
dtype: int64

In [13]:
df_melt

        id RM Category  Year  Month    Name  Value
0        1       10 rm  2009      1  C.LK98  218.0
1        2       10 rm  2009      2  C.LK98  200.0
2        3       10 rm  2009      3  C.LK98  272.0
3        4       10 rm  2009      4  C.LK98  178.0
4        5       10 rm  2009      5  C.LK98  200.0
...    ...         ...   ...    ...     ...    ...
8203  1364       75 rm  2014      8  P.NLP3    0.0
8204  1365       75 rm  2014      9  P.NLP3    0.0
8205  1366       75 rm  2014     10  P.NLP3    0.0
8206  1367       75 rm  2014     11  P.NLP3    0.0
8207  1368       75 rm  2014     12  P.NLP3    0.0

[8208 rows x 6 columns]

In [14]:
df_melt.sort_values(by=["Name", "id"], inplace=True)
df_melt

        id RM Category  Year  Month    Name  Value
2736     1       10 rm  2009      1    C.1K   56.0
2737     2       10 rm  2009      2    C.1K   44.0
2738     3       10 rm  2009      3    C.1K   52.0
2739     4       10 rm  2009      4    C.1K   42.0
2740     5       10 rm  2009      5    C.1K   60.0
...    ...         ...   ...    ...     ...    ...
8203  1364       75 rm  2014      8  P.NLP3    0.0
8204  1365       75 rm  2014      9  P.NLP3    0.0
8205  1366       75 rm  2014     10  P.NLP3    0.0
8206  1367       75 rm  2014     11  P.NLP3    0.0
8207  1368       75 rm  2014     12  P.NLP3    0.0

[8208 rows x 6 columns]

In [15]:
df_melt["3m_avg"] = df_melt["Value"].rolling(window=3).mean()
df_melt

        id RM Category  Year  Month    Name  Value        3m_avg
2736     1       10 rm  2009      1    C.1K   56.0           NaN
2737     2       10 rm  2009      2    C.1K   44.0           NaN
2738     3       10 rm  2009      3    C.1K   52.0  5.066667e+01
2739     4       10 rm  2009      4    C.1K   42.0  4.600000e+01
2740     5       10 rm  2009      5    C.1K   60.0  5.133333e+01
...    ...         ...   ...    ...     ...    ...           ...
8203  1364       75 rm  2014      8  P.NLP3    0.0  1.370629e+06
8204  1365       75 rm  2014      9  P.NLP3    0.0  0.000000e+00
8205  1366       75 rm  2014     10  P.NLP3    0.0  0.000000e+00
8206  1367       75 rm  2014     11  P.NLP3    0.0  0.000000e+00
8207  1368       75 rm  2014     12  P.NLP3    0.0  0.000000e+00

[8208 rows x 7 columns]

In [16]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)
df_melt

        id RM Category  Year  Month    Name  Value     3m_avg
2736     1       10 rm  2009      1    C.1K  56.00        NaN
2737     2       10 rm  2009      2    C.1K  44.00        NaN
2738     3       10 rm  2009      3    C.1K  52.00      50.67
2739     4       10 rm  2009      4    C.1K  42.00      46.00
2740     5       10 rm  2009      5    C.1K  60.00      51.33
...    ...         ...   ...    ...     ...    ...        ...
8203  1364       75 rm  2014      8  P.NLP3   0.00 1370629.30
8204  1365       75 rm  2014      9  P.NLP3   0.00       0.00
8205  1366       75 rm  2014     10  P.NLP3   0.00       0.00
8206  1367       75 rm  2014     11  P.NLP3   0.00       0.00
8207  1368       75 rm  2014     12  P.NLP3   0.00       0.00

[8208 rows x 7 columns]

In [17]:
df_melt["6m_avg"] = df_melt["Value"].rolling(window=6).mean()
df_melt

        id RM Category  Year  Month    Name  Value     3m_avg     6m_avg
2736     1       10 rm  2009      1    C.1K  56.00        NaN        NaN
2737     2       10 rm  2009      2    C.1K  44.00        NaN        NaN
2738     3       10 rm  2009      3    C.1K  52.00      50.67        NaN
2739     4       10 rm  2009      4    C.1K  42.00      46.00        NaN
2740     5       10 rm  2009      5    C.1K  60.00      51.33        NaN
...    ...         ...   ...    ...     ...    ...        ...        ...
8203  1364       75 rm  2014      8  P.NLP3   0.00 1370629.30 2452881.02
8204  1365       75 rm  2014      9  P.NLP3   0.00       0.00 1814921.68
8205  1366       75 rm  2014     10  P.NLP3   0.00       0.00 1261496.35
8206  1367       75 rm  2014     11  P.NLP3   0.00       0.00  685314.65
8207  1368       75 rm  2014     12  P.NLP3   0.00       0.00       0.00

[8208 rows x 8 columns]