# Challenge #10: Date Time Calculations

>For this challenge let’s look at the date and time functions in Alteryx.

>The use case:

>A distribution center receives a package. At the point of receipt, the package is scanned and a timestamp is captured for arrival date/time. The company is trying to reduce the amount of time the package is at its facility and as a result is trying to analyze how long packages remain at the facility.

>The objective for this challenge is to **calculate the delta between arrival date/time and the Time_Now field (this field has the date/time of the creation of this challenge and will be changing as time goes on). Create a unique field for Days, Hours, Minutes and Seconds.**

>We have listed this as an intermediate exercise  and I expect it will go very quickly for many of you. Let us know what you think, we are looking forward to hearing your feedback.

In [128]:
import pandas as pd
import math
from datetime import datetime

# import and preview output

output = pd.read_csv('output.csv', index_col = False)
df_output = pd.DataFrame(output)
df_output.head(10)

,Registrant ID,TIMESTAMP,Time_Now,Days,Hours,Minutes,Seconds
0,HPNZGSDMQMX,2014-07-09 11:07:47,2014-07-14 08:25:16,4,21,17,29
1,F5NZRZ3YVRD,2014-07-09 08:40:07,2014-07-14 08:25:16,4,23,45,9
2,FHNBTNMV3MP,2014-07-08 12:26:56,2014-07-14 08:25:16,5,19,58,20
3,ZHN7W97Z955,2014-07-08 13:26:38,2014-07-14 08:25:16,5,18,58,38
4,ZKNWRVBTXZ2,2014-07-08 13:25:42,2014-07-14 08:25:16,5,18,59,34
5,HGNYD3V77CQ,2014-07-07 19:13:24,2014-07-14 08:25:16,6,13,11,52
6,HJN6JRBWR3Z,2014-07-08 11:39:52,2014-07-14 08:25:16,5,20,45,24
7,KNNHPH2YTPX,2014-07-07 14:35:10,2014-07-14 08:25:16,6,17,50,6
8,JPNX3YQ5GV3,2014-07-08 10:35:18,2014-07-14 08:25:16,5,21,49,58
9,ZFN8QQ3RSP7,2014-07-07 20:00:46,2014-07-14 08:25:16,6,12,24,30

In [129]:
# import and preview input

input = pd.read_csv('input.csv', index_col = False)
df = pd.DataFrame(input)
df.head(10)

  Registrant ID            TIMESTAMP             Time_Now
0   HPNZGSDMQMX  2014-07-09 11:07:47  2014-07-14 08:25:16
1   F5NZRZ3YVRD  2014-07-09 08:40:07  2014-07-14 08:25:16
2   FHNBTNMV3MP  2014-07-08 12:26:56  2014-07-14 08:25:16
3   ZHN7W97Z955  2014-07-08 13:26:38  2014-07-14 08:25:16
4   ZKNWRVBTXZ2  2014-07-08 13:25:42  2014-07-14 08:25:16
5   HGNYD3V77CQ  2014-07-07 19:13:24  2014-07-14 08:25:16
6   HJN6JRBWR3Z  2014-07-08 11:39:52  2014-07-14 08:25:16
7   KNNHPH2YTPX  2014-07-07 14:35:10  2014-07-14 08:25:16
8   JPNX3YQ5GV3  2014-07-08 10:35:18  2014-07-14 08:25:16
9   ZFN8QQ3RSP7  2014-07-07 20:00:46  2014-07-14 08:25:16

In [130]:
def time_between(d1, d2):
    d1 = datetime.strptime(d1, "%Y-%m-%d %H:%M:%S")
    d2 = datetime.strptime(d2, "%Y-%m-%d %H:%M:%S")
    diff = abs(d2 - d1)
    days = diff.days
    hours = math.floor(diff.seconds/3600)
    minutes = math.floor((diff.seconds - hours * 3600) / 60)
    seconds = math.floor(diff.seconds - hours * 3600 - minutes * 60)
    return days, hours, minutes, seconds

In [131]:
df[['Days', 'Hours', 'Minutes', 'Seconds']] = df.apply(lambda row: time_between(row['TIMESTAMP'], row['Time_Now']), axis=1, result_type='expand')
df.head()

,Registrant ID,TIMESTAMP,Time_Now,Days,Hours,Minutes,Seconds
0,HPNZGSDMQMX,2014-07-09 11:07:47,2014-07-14 08:25:16,4,21,17,29
1,F5NZRZ3YVRD,2014-07-09 08:40:07,2014-07-14 08:25:16,4,23,45,9
2,FHNBTNMV3MP,2014-07-08 12:26:56,2014-07-14 08:25:16,5,19,58,20
3,ZHN7W97Z955,2014-07-08 13:26:38,2014-07-14 08:25:16,5,18,58,38
4,ZKNWRVBTXZ2,2014-07-08 13:25:42,2014-07-14 08:25:16,5,18,59,34

In [137]:
df.eq(output).all()

Registrant ID    True
TIMESTAMP        True
Time_Now         True
Days             True
Hours            True
Minutes          True
Seconds          True
dtype: bool