
# Challenge #8: Aggregate Consumer Purchases

### Aggregate Consumer Purchases:

>For this week’s exercise we will look at customer purchase behavior to decide if we should offer a “Meal Deal” that would add a side and drink to a purchase of pizza or a burger. The incoming data is larger than usual for these exercises so I have packaged the workflow as an Alteryx Package.

### This week’s Objective:

>In order to decide if we should start including a new "Meal Deal" on our menu we want to study the potential impact on recent transactions. **Please identify the number and percentage of orders since July 1, 2013 which include the following categories of food: Pizza OR Burger along with a Side and Drink.**

### Summary of Data:

>Point of Sale data includes the ticket level information, and the lookup table categorizes items into higher level food categories.

#### Hint:

>Don't forget to join to the lookup table and filter by date. As always we look forward to your feedback and suggestions!

In [101]:
import pandas as pd
import datetime

# import and preview output

output = pd.read_csv('output.csv', index_col = False)
df_output = pd.DataFrame(output)
df_output.head(25)

   Potential Meal Deal  Total          %
0                10964  15497  70.749177

In [102]:
# import and preview input

input = pd.read_csv('input1.csv', index_col = False)
df = pd.DataFrame(input)
df

        TicketID        Date  MemberID                 Desc  Price
0         100004  2013-01-07       NaN    Mozzarella Sticks    7.0
1         100004  2013-01-07       NaN     Jalapeno Poppers    7.0
2         100004  2013-01-07       NaN          Onion Rings    7.0
3         100004  2013-01-07       NaN          Onion Rings    7.0
4         100004  2013-01-07       NaN      Supreme - Small    9.0
...          ...         ...       ...                  ...    ...
269370    331462  2013-12-28       NaN  The Works  - Medium   14.0
269371    331462  2013-12-28       NaN         Soda - Small    2.0
269372    331462  2013-12-28       NaN         Soda - Small    2.0
269373    331462  2013-12-28       NaN         Soda - Large    3.0
269374    331462  2013-12-28       NaN         Soda - Large    3.0

[269375 rows x 5 columns]

In [103]:
# import and preview input

input2 = pd.read_csv('input2.csv', index_col = False)
df2 = pd.DataFrame(input2)
df2.head(10)

                        Desc    Type
0               Bacon Burger  Burger
1   Barbecue Chicken - Large   Pizza
2  Barbecue Chicken - Medium   Pizza
3   Barbecue Chicken - Small   Pizza
4    Buffalo Chicken - Large   Pizza
5   Buffalo Chicken - Medium   Pizza
6    Buffalo Chicken - Small   Pizza
7              Caprese Salad   Salad
8               Cheese Bread    Side
9              Cheese Burger  Burger

In [104]:
df.sort_values(by='Date')['Date'].unique()

array(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
       '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08',
       '2013-01-09', '2013-01-10', '2013-01-11', '2013-01-12',
       '2013-01-13', '2013-01-14', '2013-01-15', '2013-01-16',
       '2013-01-17', '2013-01-18', '2013-01-19', '2013-01-20',
       '2013-01-21', '2013-01-22', '2013-01-23', '2013-01-24',
       '2013-01-25', '2013-01-26', '2013-01-27', '2013-01-28',
       '2013-01-29', '2013-01-30', '2013-01-31', '2013-02-01',
       '2013-02-02', '2013-02-03', '2013-02-04', '2013-02-05',
       '2013-02-06', '2013-02-07', '2013-02-08', '2013-02-09',
       '2013-02-10', '2013-02-11', '2013-02-12', '2013-02-13',
       '2013-02-14', '2013-02-15', '2013-02-16', '2013-02-17',
       '2013-02-18', '2013-02-19', '2013-02-20', '2013-02-21',
       '2013-02-22', '2013-02-23', '2013-02-24', '2013-02-25',
       '2013-02-26', '2013-02-27', '2013-02-28', '2013-03-01',
       '2013-03-02', '2013-03-03', '2013-03-04', '2013-03-05',
       '2013-03-06', '2013-03-07', '2013-03-08', '2013-03-09',
       '2013-03-10', '2013-03-11', '2013-03-12', '2013-03-13',
       '2013-03-14', '2013-03-15', '2013-03-16', '2013-03-17',
       '2013-03-18', '2013-03-19', '2013-03-20', '2013-03-21',
       '2013-03-22', '2013-03-23', '2013-03-24', '2013-03-25',
       '2013-03-26', '2013-03-27', '2013-03-28', '2013-03-29',
       '2013-03-30', '2013-03-31', '2013-04-01', '2013-04-02',
       '2013-04-03', '2013-04-04', '2013-04-05', '2013-04-06',
       '2013-04-07', '2013-04-08', '2013-04-09', '2013-04-10',
       '2013-04-11', '2013-04-12', '2013-04-13', '2013-04-14',
       '2013-04-15', '2013-04-16', '2013-04-17', '2013-04-18',
       '2013-04-19', '2013-04-20', '2013-04-21', '2013-04-22',
       '2013-04-23', '2013-04-24', '2013-04-25', '2013-04-26',
       '2013-04-27', '2013-04-28', '2013-04-29', '2013-04-30',
       '2013-05-01', '2013-05-02', '2013-05-03', '2013-05-04',
       '2013-05-05', '2013-05-06', '2013-05-07', '2013-05-08',
       '2013-05-09', '2013-05-10', '2013-05-11', '2013-05-12',
       '2013-05-13', '2013-05-14', '2013-05-15', '2013-05-16',
       '2013-05-17', '2013-05-18', '2013-05-19', '2013-05-20',
       '2013-05-21', '2013-05-22', '2013-05-23', '2013-05-24',
       '2013-05-25', '2013-05-26', '2013-05-27', '2013-05-28',
       '2013-05-29', '2013-05-30', '2013-05-31', '2013-06-01',
       '2013-06-02', '2013-06-03', '2013-06-04', '2013-06-05',
       '2013-06-06', '2013-06-07', '2013-06-08', '2013-06-09',
       '2013-06-10', '2013-06-11', '2013-06-12', '2013-06-13',
       '2013-06-14', '2013-06-15', '2013-06-16', '2013-06-17',
       '2013-06-18', '2013-06-19', '2013-06-20', '2013-06-21',
       '2013-06-22', '2013-06-23', '2013-06-24', '2013-06-25',
       '2013-06-26', '2013-06-27', '2013-06-28', '2013-06-29',
       '2013-06-30', '2013-07-01', '2013-07-02', '2013-07-03',
       '2013-07-04', '2013-07-05', '2013-07-06', '2013-07-07',
       '2013-07-08', '2013-07-09', '2013-07-10', '2013-07-11',
       '2013-07-12', '2013-07-13', '2013-07-14', '2013-07-15',
       '2013-07-16', '2013-07-17', '2013-07-18', '2013-07-19',
       '2013-07-20', '2013-07-21', '2013-07-22', '2013-07-23',
       '2013-07-24', '2013-07-25', '2013-07-26', '2013-07-27',
       '2013-07-28', '2013-07-29', '2013-07-30', '2013-07-31',
       '2013-08-01', '2013-08-02', '2013-08-03', '2013-08-04',
       '2013-08-05', '2013-08-06', '2013-08-07', '2013-08-08',
       '2013-08-09', '2013-08-10', '2013-08-11', '2013-08-12',
       '2013-08-13', '2013-08-14', '2013-08-15', '2013-08-16',
       '2013-08-17', '2013-08-18', '2013-08-19', '2013-08-20',
       '2013-08-21', '2013-08-22', '2013-08-23', '2013-08-24',
       '2013-08-25', '2013-08-26', '2013-08-27', '2013-08-28',
       '2013-08-29', '2013-08-30', '2013-08-31', '2013-09-01',
       '2013-09-02', '2013-09-03', '2013-09-04', '2013-09-05',
       '2013-09-06', '2013-09-07', '2013-09-08', '2013-09-09',
       '2013-09-10', '2013-09-11', '2013-09-12', '2013-09-13',
       '2013-09-14', '2013-09-15', '2013-09-16', '2013-09-17',
       '2013-09-18', '2013-09-19', '2013-09-20', '2013-09-21',
       '2013-09-22', '2013-09-23', '2013-09-24', '2013-09-25',
       '2013-09-26', '2013-09-27', '2013-09-28', '2013-09-29',
       '2013-09-30', '2013-10-01', '2013-10-02', '2013-10-03',
       '2013-10-04', '2013-10-05', '2013-10-06', '2013-10-07',
       '2013-10-08', '2013-10-09', '2013-10-10', '2013-10-11',
       '2013-10-12', '2013-10-13', '2013-10-14', '2013-10-15',
       '2013-10-16', '2013-10-17', '2013-10-18', '2013-10-19',
       '2013-10-20', '2013-10-21', '2013-10-22', '2013-10-23',
       '2013-10-24', '2013-10-25', '2013-10-26', '2013-10-27',
       '2013-10-28', '2013-10-29', '2013-10-30', '2013-10-31',
       '2013-11-01', '2013-11-02', '2013-11-03', '2013-11-04',
       '2013-11-05', '2013-11-06', '2013-11-07', '2013-11-08',
       '2013-11-09', '2013-11-10', '2013-11-11', '2013-11-12',
       '2013-11-13', '2013-11-14', '2013-11-15', '2013-11-16',
       '2013-11-17', '2013-11-18', '2013-11-19', '2013-11-20',
       '2013-11-21', '2013-11-22', '2013-11-23', '2013-11-24',
       '2013-11-25', '2013-11-26', '2013-11-27', '2013-11-28',
       '2013-11-29', '2013-11-30', '2013-12-01', '2013-12-02',
       '2013-12-03', '2013-12-04', '2013-12-05', '2013-12-06',
       '2013-12-07', '2013-12-08', '2013-12-09', '2013-12-10',
       '2013-12-11', '2013-12-12', '2013-12-13', '2013-12-14',
       '2013-12-15', '2013-12-16', '2013-12-17', '2013-12-18',
       '2013-12-19', '2013-12-20', '2013-12-21', '2013-12-22',
       '2013-12-23', '2013-12-24', '2013-12-25', '2013-12-26',
       '2013-12-27', '2013-12-28', '2013-12-29', '2013-12-30',
       '2013-12-31'], dtype=object)

In [105]:
df['Date'] = pd.to_datetime(df['Date'], format="%Y-%m-%d")
df = df[df['Date'] >= datetime.datetime(2013, 6, 1)]
df

        TicketID       Date  MemberID                   Desc  Price
5528      101964 2013-06-03       NaN      Mozzarella Sticks    7.0
5529      101964 2013-06-03       NaN              Stromboli    7.5
5530      101964 2013-06-03       NaN     House Salad - Half    3.0
5531      101964 2013-06-03       NaN    House Salad - Whole    6.0
5532      101964 2013-06-03       NaN  Garden Fresh - Medium   14.0
...          ...        ...       ...                    ...    ...
269370    331462 2013-12-28       NaN    The Works  - Medium   14.0
269371    331462 2013-12-28       NaN           Soda - Small    2.0
269372    331462 2013-12-28       NaN           Soda - Small    2.0
269373    331462 2013-12-28       NaN           Soda - Large    3.0
269374    331462 2013-12-28       NaN           Soda - Large    3.0

[157216 rows x 5 columns]

In [106]:
df.sort_values(by='Date')['Date'].unique()

<DatetimeArray>
['2013-06-01 00:00:00', '2013-06-02 00:00:00', '2013-06-03 00:00:00',
 '2013-06-04 00:00:00', '2013-06-05 00:00:00', '2013-06-06 00:00:00',
 '2013-06-07 00:00:00', '2013-06-08 00:00:00', '2013-06-09 00:00:00',
 '2013-06-10 00:00:00',
 ...
 '2013-12-22 00:00:00', '2013-12-23 00:00:00', '2013-12-24 00:00:00',
 '2013-12-25 00:00:00', '2013-12-26 00:00:00', '2013-12-27 00:00:00',
 '2013-12-28 00:00:00', '2013-12-29 00:00:00', '2013-12-30 00:00:00',
 '2013-12-31 00:00:00']
Length: 214, dtype: datetime64[ns]

- join data together
- group by order, aggregate item types
- filter to records with [[Pizza | Burger] & Side & Drink]
- count, get percent of total

In [107]:
df_merge = df.merge(df2, on='Desc')
df_merge.head(12)

    TicketID       Date  MemberID                     Desc  Price   Type
0     101964 2013-06-03       NaN        Mozzarella Sticks    7.0   Side
1     101964 2013-06-03       NaN                Stromboli    7.5  Pizza
2     101964 2013-06-03       NaN       House Salad - Half    3.0  Salad
3     101964 2013-06-03       NaN      House Salad - Whole    6.0  Salad
4     101964 2013-06-03       NaN    Garden Fresh - Medium   14.0  Salad
5     101964 2013-06-03       NaN     Garden Fresh - Large   16.0  Salad
6     101964 2013-06-03       NaN       The Works  - Small    9.0  Pizza
7     101964 2013-06-03       NaN  Buffalo Chicken - Small    9.0  Pizza
8     101964 2013-06-03       NaN             Soda - Small    2.0  Drink
9     101964 2013-06-03       NaN             Soda - Large    3.0  Drink
10    101966 2013-06-03  998870.0        Mozzarella Sticks    7.0   Side
11    101966 2013-06-03  998870.0                Stromboli    7.5  Pizza

In [123]:
df_group = df_merge.groupby(by=['TicketID', 'Date'])['Type'].apply(lambda x: ','.join(x)).reset_index()
df_group

       TicketID       Date                                               Type
0        101964 2013-06-03  Side,Pizza,Salad,Salad,Salad,Salad,Pizza,Pizza...
1        101966 2013-06-03  Side,Pizza,Side,Side,Salad,Salad,Burger,Pizza,...
2        101969 2013-06-03                  Soup,Soup,Pizza,Pizza,Drink,Drink
3        101979 2013-06-03  Pizza,Side,Soup,Soup,Salad,Burger,Burger,Pizza...
4        101982 2013-06-03                     Burger,Pizza,Pizza,Drink,Drink
...         ...        ...                                                ...
17972    331453 2013-12-28          Salad,Salad,Salad,Pizza,Pizza,Pizza,Drink
17973    331454 2013-12-28      Side,Side,Salad,Pizza,Pizza,Pizza,Pizza,Drink
17974    331459 2013-12-28         Pizza,Burger,Pizza,Pizza,Drink,Drink,Drink
17975    331461 2013-12-28            Side,Side,Salad,Pizza,Pizza,Pizza,Drink
17976    331462 2013-12-28  Side,Side,Salad,Salad,Burger,Pizza,Salad,Pizza...

[17977 rows x 3 columns]

In [124]:
df_deal = df_group[(df_group['Type'].str.contains('Burger|Pizza', regex=True)) & (df_group['Type'].str.contains('Side')) & (df_group['Type'].str.contains('Drink'))]
df_deal

       TicketID       Date                                               Type
0        101964 2013-06-03  Side,Pizza,Salad,Salad,Salad,Salad,Pizza,Pizza...
1        101966 2013-06-03  Side,Pizza,Side,Side,Salad,Salad,Burger,Pizza,...
3        101979 2013-06-03  Pizza,Side,Soup,Soup,Salad,Burger,Burger,Pizza...
6        101993 2013-06-03  Side,Side,Soup,Salad,Salad,Burger,Pizza,Pizza,...
7        101995 2013-06-03  Side,Pizza,Side,Soup,Salad,Salad,Salad,Pizza,P...
...         ...        ...                                                ...
17969    331446 2013-12-28  Side,Side,Side,Side,Side,Pizza,Pizza,Pizza,Piz...
17970    331447 2013-12-28          Side,Burger,Pizza,Pizza,Pizza,Drink,Drink
17973    331454 2013-12-28      Side,Side,Salad,Pizza,Pizza,Pizza,Pizza,Drink
17975    331461 2013-12-28            Side,Side,Salad,Pizza,Pizza,Pizza,Drink
17976    331462 2013-12-28  Side,Side,Salad,Salad,Burger,Pizza,Salad,Pizza...

[12751 rows x 3 columns]

In [125]:
df.groupby(by='TicketID').sum('Price')
df

        TicketID       Date  MemberID                   Desc  Price
5528      101964 2013-06-03       NaN      Mozzarella Sticks    7.0
5529      101964 2013-06-03       NaN              Stromboli    7.5
5530      101964 2013-06-03       NaN     House Salad - Half    3.0
5531      101964 2013-06-03       NaN    House Salad - Whole    6.0
5532      101964 2013-06-03       NaN  Garden Fresh - Medium   14.0
...          ...        ...       ...                    ...    ...
269370    331462 2013-12-28       NaN    The Works  - Medium   14.0
269371    331462 2013-12-28       NaN           Soda - Small    2.0
269372    331462 2013-12-28       NaN           Soda - Small    2.0
269373    331462 2013-12-28       NaN           Soda - Large    3.0
269374    331462 2013-12-28       NaN           Soda - Large    3.0

[157216 rows x 5 columns]

In [126]:
results = pd.DataFrame({'Potential Meal Deal': [df_deal.count()['TicketID']], 'Total': [df.count()['TicketID']]})
results['%'] = results['Potential Meal Deal'] / results['Total']
results

   Potential Meal Deal   Total         %
0                12751  157216  0.081105