# Challenge #5: HR Position Finder Application

>We hope you enjoyed last week's challenge. For the fifth challenge let’s look at building an analytic application.

>An HR department has a defined hierarchy for job identification across the organization. Depending on the job, the position within the hierarchy can change.

>The goal is to **create an analytical application that allows a HR rep to enter a position # (in this example, 33333) and return all records where the position is found within the hierarchy system.**

>We have listed this as an intermediate challenge since parameterizing a workflow and converting it to an application is slightly more advanced however the workflow to answer the question should be beginner level. As always, we love to hear your comments. We hope you are having fun with the challenges!

In [41]:
import pandas as pd

# import and preview output

output = pd.read_csv('output.csv', index_col = False)
df_output = pd.DataFrame(output)
df_output.head(25)

   Position Number  Level0  Level1  Level2  Level3
0            33333  123456  111111   22222   33333
1            33333  123456   12222   33333   36677
2            33333  123456   33333  235555  388888

In [42]:
# import and preview input

input = pd.read_csv('input.csv', index_col = False)
df = pd.DataFrame(input)

pd.options.display.float_format = '{:.0f}'.format
df.head(25)

    Level0  Level1  Level2  Level3
0   123456     NaN     NaN     NaN
1   123456  111111     NaN     NaN
2   123456  111111   22222     NaN
3   123456  111111   22222   33333
4   123456  111111   23333     NaN
5   123456  111111   23333   34444
6   123456  111111   23333   35555
7   123456   12222     NaN     NaN
8   123456   12222  234444     NaN
9   123456   12222  234444  366666
10  123456   12222   33333   36677
11  123456   12222  234444   37777
12  123456   12222     NaN     NaN
13  123456   12222  235555     NaN
14  123456   12222  235555  388888
15  123456   12222  235555  399999
16  123456   12222  235555  399888
17  123456   12222  235555 3998877
18  123456   33333  235555  388888

### All possible values for position number

In [66]:
print(pd.unique(df.values.flatten()))

[ 123456.      nan  111111.   22222.   33333.   23333.   34444.   35555.
   12222.  234444.  366666.   36677.   37777.  235555.  388888.  399999.
  399888. 3998877.]

## "App"

In [ ]:
# Enter position number here:

position_number = 12222

In [ ]:
print(df[df.isin([position_number]).any(axis=1)])

    Level0  Level1  Level2  Level3
7   123456   12222     NaN     NaN
8   123456   12222  234444     NaN
9   123456   12222  234444  366666
10  123456   12222   33333   36677
11  123456   12222  234444   37777
12  123456   12222     NaN     NaN
13  123456   12222  235555     NaN
14  123456   12222  235555  388888
15  123456   12222  235555  399999
16  123456   12222  235555  399888
17  123456   12222  235555 3998877